services:
  api:
    image: ghcr.io/petry-tech/petry-tech-examples-py:latest
    ports:
      - "8080:8080"
    volumes:
      - "~/logs/petry-tech-examples-py.log:/app/app.log"
    deploy:
      restart_policy:
        condition: on-failure
