name: build_and_push

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      ORG: petry-ai
      IMAGE: petry-tech-examples-py
    steps:
      - name: Checkout petry-tech-examples-py
        uses: actions/checkout@v3
        with:
          repository: "petry-ai/petry-tech-examples-py"
          ssh-key: ${{ secrets.PETRY_TECH_EXAMPLES_PY_SSH }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          ./run-tests.sh

      - name: Setyp Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: SSH Agent
        uses: webfactory/ssh-agent@v0.4.1
        with:
          ssh-private-key: ${{ secrets.PETRY_TECH_EXAMPLES_PY_SSH }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push docker iamge
        uses: docker/build-push-action@v2
        with:
          push: true
          ssh: github=${{ env.SSH_AUTH_SOCK }}
          build-args: |
            ENV=production
            OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}
            ALLOWED_HOST=${{ secrets.ALLOWED_HOST }}
          tags: |
            ghcr.io/${{ env.ORG }}/${{ env.IMAGE }}:latest
